### ISSUE TITLE
Предложение по расширению функционала

### ISSUE THREAD

**Issue by MalfurionST** [GyverLibs/SunPosition#1]
Очень интересная библиотека, но мне кажется сюда надо добавить возможность расчета времени восхода и захода солнца...
А слиб она ещё могла показать даты равноденствия и солнцестояния то было бы вообще отлично...
Но я в таких расчетах не силен...

**Comment by GyverLibs** [comment]
Я тоже не силён :) наткнулся на готовый алгоритм. Время заката/равноденствия можно брать из библиотеки TimeLord, там вроде нормально реализовано
