### ISSUE TITLE
а для луны расчетов нет?

### ISSUE THREAD

**Issue by MalfurionST** [GyverLibs/SunPosition#2]
Кучу сайтов облазил но не нашел готового решения для расчета времени восхода и захода луны...

**Comment by GyverLibs** [comment]
Ну, название библиотеки намекает только на солнце)

**Comment by GyverLibs** [comment]
В либе TimeLord вроде луна есть

**Comment by MalfurionST** [comment]
там только фаза

**Comment by MalfurionST** [comment]
и если не секрет не сравнивали точность Вашей библиотеки и TimeLord между собой?

**Comment by GyverLibs** [comment]
Я сравнивал с https://www.suncalc.org/ . Плюс у меня два алгоритма, если выбрать более точный - там точность вообще дл долей градуса

**Comment by MalfurionST** [comment]
ок спс для расчетов луны только нашел книгу но пока руки не дошли до нее (Даффет-Смит Практическая астрономия с калькулятором), попробую высчитать от зенита солнца и фазы луны, может что получится...

**Comment by MalfurionST** [comment]
Нашёл библиотеку для расчетов восхода и захода луны, просто на Вашем сайте в разделе библиотек её нет...
https://www.arduino.cc/reference/en/libraries/moonrise/

**Comment by GyverLibs** [comment]
У меня на сайте указан дайбох 1% существующих библиотек из официального списка)
